### PR TITLE
Allows search of HKCU

### PR DESCRIPTION
**Pull request by TongZhai**
-NavtiveUtility: search HKCU if HKLM is empty
-Registries: add a getter of the realKey so as to test against null
-REngineInitTest: update unit test for the new getter function
-address #115

### CODE REVIEW

**Comment by lrasmus** [comment]
Thanks @TongZhai!  I took a look, and it seems that your code duplicates parts of [some existing code](https://github.com/rdotnet/rdotnet/pull/116/files#diff-84689d829522ffeeef42fefe7709ad95L511-L517).  

I think a potential problem is that if `rCore` is null, we [would throw an unexpected exception here](https://github.com/rdotnet/rdotnet/pull/116/files#diff-84689d829522ffeeef42fefe7709ad95R511).

What if we [changed the existing line 511](https://github.com/rdotnet/rdotnet/pull/116/files#diff-84689d829522ffeeef42fefe7709ad95L511) to be something like:

```
if (rCore == null || rCore.GetRealKey() is null)
```

That would add a check for the condition you noted, and reuse the existing logging and error handling code.

**Comment by TongZhai** [comment]
But the goal is to have another try to actually "find" the R registry in HKCU to make it work, detecting if it is not in HKLM alone is not ideal as it is almost saying we only recognize if R is saved in HKLM, which is in-itself doesn't constitute as a grave error, but the fact that you have HKCU and HKLM infrastructure in your code base already means we should utilize them to make this process work as much as possible.

**Comment by lrasmus** [comment]
Thanks for the reply @TongZhai - what I didn't realize (sorry for not investigating this fully before), is that `OpenSubKey` [appears to always return an object, and never null](https://github.com/rdotnet/rdotnet/blob/ff006e13c167a4a7d1dfa5e0c25059b2b8fb4260/R.NET/NativeLibrary/Registries.cs#L124).  I was concerned that we'd have a situation where `rCore` would have been null and this change is trying to access `GetRealKey`, but it doesn't look like that can ever happen.

**Comment by TongZhai** [comment]
@lrasmus Your suggestion is good so I made the update above to have a better sequential testing of r-core registry key in HKLM then HKCU. Hope this is good PR endpoint.

**Comment by lrasmus** [comment]
Thanks @TongZhai!  I think this looks good.  Am hoping @jmp75 can also review soon and consider merging the PR.

**Pull request merged**
