### PR TITLE
Rdotnet master

### PR DESCRIPTION
**Pull request by danielleiszen**

### CODE REVIEW

**Comment by danielleiszen** [comment]
merge than

**Comment by danielleiszen** [comment]
Sorry, I managed to switch repos somehow. I wanted to merge to my fork.

**Comment by lrasmus** [comment]
@danielleiszen - thanks for submitting this, I was wondering if there was a brief summary of what should be tested?  Looks like specifically this was for .NET Core, right?  And there were a few problems you found with the original StatTag/altrep fixes?

**Comment by danielleiszen** [comment]
@lrasmus - sorry, this is my bad. I did not intend to do so. I forked the repo for myself a few months ago and I wanted to create a pull request to migrate the changes you guys created since my fork was created. somehow I managed to switch repos and I created the pull request to the original. I am really sorry about that. 

Originally my aim was to create a NETStandard compatible version of the original repo. I applied the  ALTREP fix and made a few changes in order to execute on CentOS in a docker container - the "getDLLVersion" API does not exist.

The two important two commits are:
https://github.com/danielleiszen/rdotnet/commit/d800c2ca2500a94675de7376da61fe05f0f522d2
and 
https://github.com/danielleiszen/rdotnet/commit/ea84d6ed1990f611de13960c3db3ad07594d2374

If you want me to create some tests, I would be happy to do so. I just need some guidance on that.
Please let me know how I could help.

**Comment by lrasmus** [comment]
Oh no worries @danielleiszen!  Thanks for the additional info and pointers to the commits.  It sounds like this could be useful to others.  I think for testing it's just making sure we're going down the paths of the if/else.  I'll admit I'm exclusively using R.NET on Windows, but I think for cross-platform testing we just need to run the test suite in the different OSes.  @jmp75 - what do you think?

**Pull request closed without merging**
